baseURL = 'https://hyperstable.github.io/'
languageCode = 'en-us'
title = 'Hyperstable'
theme = 'hugo-book'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.extensions]
KaTeX = true
