baseURL = 'https://docs.hyperstable.xyz/'
languageCode = 'en-us'
title = 'Hyperstable'
theme = 'lotusdocs'

# Still need modules for Bootstrap dependency
[module]
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

# This is required by the theme
[markup.goldmark.renderer]
  unsafe = true

# Theme parameters
[params]
  [params.flexSearch]
    enabled = false

[params.ui]
  opengraph = false

# Menu configuration
[[menu.primary]]
  name  = "Hyperstable Docs"
  url = "/docs/"
  identifier = "docs"
  weight = 10
