baseURL = "https://docs.hyperstable.xyz/"
languageCode = "en-us"
title = "Hyperstable"

# Enable Git info for last modified dates
enableGitInfo = true

# Language settings
contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true

# Highlighting
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "tango"

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[languages]
[languages.en]
languageName = "English"
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango"

# Site params
[params]
katex = true
copyright = "Hyperstable"
github_repo = "https://github.com/hyperstable/hyperstable.github.io"
github_project_repo = "https://github.com/hyperstable/hyperstable.github.io"

# Enable users to edit pages
github_branch = "main"
github_subdir = "content"

# Google Custom Search Engine ID
# gcs_engine_id = ""

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons
prism_syntax_highlighting = false

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Make sidebar foldable
sidebar_menu_foldable = true
# Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to hide the sidebar search box
sidebar_search_disable = false
# Set to false if you don't want to display a logo in the top nav bar
navbar_logo = true
# Set to true to disable the About link in footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc.
[params.ui.feedback]
enable = false

# Adds a reading time to the top of each doc.
[params.ui.readingtime]
enable = true

[params.links]
# End user relevant links
[[params.links.user]]
  name = "GitHub"
  url = "https://github.com/hyperstable"
  icon = "fab fa-github"
  desc = "Hyperstable on GitHub"

[[params.links.user]]
  name = "Twitter"
  url = "https://twitter.com/hyperstable"
  icon = "fab fa-twitter"
  desc = "Follow us on Twitter"

# Developer relevant links
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/hyperstable/hyperstable.github.io"
  icon = "fab fa-github"
  desc = "Development takes place here!"

# Docsy theme
[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false
