baseURL = 'http://docs.hyperstable.xyz/'
languageCode = 'en-us'
title = 'Hyperstable'

# The LotusDocs theme recommends this setting for its features
[markup.goldmark.renderer]
  unsafe = true

[module]
  [[module.imports]]
    # This line updates the theme to the latest version and fixes the bugs
    path = "github.com/colinwilson/lotusdocs/v5"

[[menu.primary]]
  name  = "Hyperstable Docs"
  url = "/docs/"
  identifier = "docs"
  weight = 10
